{
    "metadata": {
        "kernelspec": {
            "name": "SQL",
            "display_name": "SQL",
            "language": "sql"
        },
        "language_info": {
            "name": "sql",
            "version": ""
        }
    },
    "nbformat_minor": 2,
    "nbformat": 4,
    "cells": [
        {
            "cell_type": "code",
            "source": [
                "USE Northwind\r\n",
                "GO"
            ],
            "metadata": {
                "azdata_cell_guid": "1a3df94f-8108-482f-af82-35ebca779453",
                "language": "sql"
            },
            "outputs": [],
            "execution_count": null
        },
        {
            "cell_type": "code",
            "source": [
                "\n",
                "--1. List all cities that have both Employees and Customers.\n",
                "SELECT DISTINCT e.City\n",
                "FROM Employees e\n",
                "JOIN Customers c ON e.City = c.City\n",
                "\n",
                "--2. List all cities that have Customers but no Employee.\n",
                "--a. with a subquery\n",
                "SELECT DISTINCT c.City\n",
                "FROM Customers c\n",
                "WHERE c.City NOT IN (SELECT e.City FROM Employees e)\n",
                "\n",
                "--b. with a join\n",
                "SELECT DISTINCT c.City\n",
                "FROM Customers c\n",
                "LEFT JOIN Employees e ON c.City = e.City\n",
                "WHERE e.City IS NULL\n",
                "\n",
                "--3. List all products and their total order quantities throughout all orders.\n",
                "SELECT p.ProductName, SUM(od.Quantity) AS TotalQuantity\n",
                "FROM [Order Details] od\n",
                "JOIN Products p ON od.ProductID = p.ProductID\n",
                "GROUP BY p.ProductName\n",
                "\n",
                "--4. List all Customer Cities and total products ordered by that city.\n",
                "SELECT c.City, SUM(od.Quantity) AS TotalProductsOrdered\n",
                "FROM Orders o\n",
                "JOIN Customers c ON o.CustomerID = c.CustomerID\n",
                "JOIN [Order Details] od ON o.OrderID = od.OrderID\n",
                "GROUP BY c.City\n",
                "\n",
                "--5. List all Customer Cities that have at least two customers.\n",
                "--a. Use union\n",
                "SELECT City\n",
                "FROM Customers\n",
                "GROUP BY City\n",
                "HAVING COUNT(CustomerID) >= 2\n",
                "\n",
                "--b. Use sub-query and no union\n",
                "SELECT DISTINCT City\n",
                "FROM (\n",
                "    SELECT City\n",
                "    FROM Customers\n",
                "    GROUP BY City\n",
                "    HAVING COUNT(CustomerID) >= 2\n",
                ") AS SubQuery\n",
                "\n",
                "--6. List all Customer Cities that have ordered at least two different kinds of products.\n",
                "SELECT c.City\n",
                "FROM Orders o\n",
                "JOIN Customers c ON o.CustomerID = c.CustomerID\n",
                "JOIN [Order Details] od ON o.OrderID = od.OrderID\n",
                "GROUP BY c.City\n",
                "HAVING COUNT(DISTINCT od.ProductID) >= 2\n",
                "\n",
                "--7. List all Customers who have ordered products, but have the ‘ship city’ on the order different from their own customer cities.\n",
                "SELECT DISTINCT c.CustomerID, c.ContactName\n",
                "FROM Customers c\n",
                "JOIN Orders o ON c.CustomerID = o.CustomerID\n",
                "WHERE c.City != o.ShipCity\n",
                "\n",
                "--8. List 5 most popular products, their average price, and the customer city that ordered most quantity of it.\n",
                "SELECT TOP 5\n",
                "    p.ProductName,\n",
                "    AVG(od.UnitPrice) AS AveragePrice,\n",
                "    c.City,\n",
                "    SUM(od.Quantity) AS TotalQuantity\n",
                "FROM [Order Details] od\n",
                "JOIN Products p ON od.ProductID = p.ProductID\n",
                "JOIN Orders o ON od.OrderID = o.OrderID\n",
                "JOIN Customers c ON o.CustomerID = c.CustomerID\n",
                "GROUP BY p.ProductName, c.City\n",
                "ORDER BY SUM(od.Quantity) DESC\n",
                "\n",
                "--9. List all cities that have never ordered something but we have employees there.\n",
                "--a. use subquery\n",
                "SELECT DISTINCT e.City\n",
                "FROM Employees e\n",
                "WHERE e.City NOT IN (SELECT c.City FROM Customers c JOIN Orders o ON c.CustomerID = o.CustomerID)\n",
                "\n",
                "--b. use join\n",
                "SELECT DISTINCT e.City\n",
                "FROM Employees e\n",
                "LEFT JOIN (\n",
                "    SELECT DISTINCT c.City\n",
                "    FROM Customers c\n",
                "    JOIN Orders o ON c.CustomerID = o.CustomerID\n",
                ") co ON e.City = co.City\n",
                "WHERE co.City IS NULL\n",
                "\n",
                "--10. List one city, if exists, that is the city from where the employee sold most orders (not the product quantity) is, and also the city of most total quantity of products ordered from.\n",
                "WITH EmployeeCity AS (\n",
                "    SELECT e.City, COUNT(o.OrderID) AS OrderCount\n",
                "    FROM Orders o\n",
                "    JOIN Employees e ON o.EmployeeID = e.EmployeeID\n",
                "    GROUP BY e.City\n",
                "),\n",
                "CustomerCity AS (\n",
                "    SELECT c.City, SUM(od.Quantity) AS TotalQuantity\n",
                "    FROM Orders o\n",
                "    JOIN Customers c ON o.CustomerID = c.CustomerID\n",
                "    JOIN [Order Details] od ON o.OrderID = od.OrderID\n",
                "    GROUP BY c.City\n",
                ")\n",
                "SELECT TOP 1 EmployeeCity.City\n",
                "FROM EmployeeCity\n",
                "JOIN CustomerCity ON EmployeeCity.City = CustomerCity.City\n",
                "ORDER BY EmployeeCity.OrderCount DESC, CustomerCity.TotalQuantity DESC\n",
                "\n",
                "--11. How do you remove the duplicates record of a table?\n",
                "--To remove duplicate records from a table, we can use the ROW_NUMBER() window function to identify duplicates and then delete them.\n",
                "--for example:\n",
                "--WITH CTE AS (\n",
                "    --SELECT *,\n",
                "       --    ROW_NUMBER() OVER (PARTITION BY Column1, Column2, Column3 ORDER BY (SELECT NULL)) AS rn\n",
                "    --FROM TableName\n",
                "--)\n",
                "--DELETE FROM CTE\n",
                "--WHERE rn > 1"
            ],
            "metadata": {
                "azdata_cell_guid": "2d75f705-47a4-430b-bfbd-4be85242098a",
                "language": "sql"
            },
            "outputs": [],
            "execution_count": null
        }
    ]
}